version: '3'
services:
 db:
  image: postgres:13
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: oms_api_development

 web:
  build: 
   context: .
   dockerfile: dockerfile
  restart: always

  volumes: 
      - .:/myapp
  ports:
      - 3000:3000
  depends_on:
      - db