version: '3'
services:
  db:
    image: postgres:14.1
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oms_api_development

  web:
    image: wintogeno/docker_aws  # Use the existing image
    restart: always
    volumes: 
      - .:/myapp/voloumes
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db/oms_api_development
volumes:
  db_data:

